compressionLevel: mixed

enableTransparentWorkspaces: false

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://mskelton.dev/yarn-outdated/v2'

supportedArchitectures:
  libc:
    - current
    - libc
    - musl
  os:
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.2.2.cjs
