export enum EditorPluginType {
  Anchor = 'anchor',
  Article = 'article',
  Audio = 'audio',
  ArticleIntroduction = 'articleIntroduction',
  Blockquote = 'blockquote',
  Box = 'box',
  Equations = 'equations',
  Geogebra = 'geogebra',
  H5p = 'h5p',
  Highlight = 'highlight',
  Image = 'image',
  Important = 'important',
  Injection = 'injection',
  Layout = 'layout',
  Multimedia = 'multimedia',

  PageLayout = 'pageLayout',
  PagePartners = 'pagePartners',
  PageTeam = 'pageTeam',
  PasteHack = 'pasteHack',

  Rows = 'rows',
  SerloTable = 'serloTable',
  Spoiler = 'spoiler',
  Table = 'table',
  Text = 'text',
  Video = 'video',

  Exercise = 'exercise',
  ScMcExercise = 'scMcExercise',
  InputExercise = 'inputExercise',
  Solution = 'solution',

  Unsupported = 'unsupported',
}
