import { MapItemsRecord } from './types'

export const localStorageKey = 'lernpfad_prototype'

export const initialMapItemsData: MapItemsRecord = {
  intro: {
    type: 'start',
    done: false,
    time: 5,
    title: 'Start',
    labels: ['group'],
    contentType: 'Inhalt',
    nextExercises: ['extra1', 'info'],
    dependsOn: null,
    position: {
      x: 45.5,
      y: 23,
    },
  },
  fork1: {
    type: 'fork',
    done: false,
    nextExercises: ['extra1', 'info'],
    dependsOn: ['intro'],
    position: {
      x: 20,
      y: 0,
    },
  },
  extra1: {
    type: 'excursion',
    done: false,
    time: 5,
    title: 'Useful phrases & vocabulary',
    labels: ['solo'],
    contentType: 'Übung',
    isMacroadaptive: true,
    nextExercises: null,
    dependsOn: ['fork1'],
    position: {
      x: 33,
      y: 20,
    },
  },
  info: {
    type: 'info',
    done: false,
    time: 5,
    title: 'Information',
    labels: ['solo'],
    contentType: 'Inhalt',
    nextExercises: ['fork2'],
    dependsOn: ['fork1'],
    position: {
      x: 45,
      y: 35,
    },
  },
  fork2: {
    type: 'fork',
    done: false,
    nextExercises: ['recap_easy', 'recap_hard'],
    dependsOn: ['info'],
    position: {
      x: 40,
      y: 0,
    },
  },
  recap_easy: {
    type: 'recap',
    done: false,
    time: 10,
    title: 'Cats or Dogs? 🐱 🐶',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: ['writing_easy'],
    dependsOn: ['fork2'],
    position: {
      x: 34,
      y: 31.5,
    },
  },
  recap_hard: {
    type: 'recap',
    done: false,
    time: 10,
    title: 'Cats or Dogs? 🐱 🐶',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: ['writing_hard'],
    dependsOn: ['fork2'],
    position: {
      x: 58,
      y: 27,
    },
  },
  writing_easy: {
    type: 'write',
    done: false,
    time: 20,
    title: 'Writing your opinion',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: ['rewrite'],
    dependsOn: ['recap_easy'],
    position: {
      x: 33.5,
      y: 51,
    },
  },
  writing_hard: {
    type: 'write',
    done: false,
    time: 20,
    title: 'Writing your opinion',
    labels: ['solo'],
    contentType: 'Übung',
    isMacroadaptive: true,
    nextExercises: ['rewrite'],
    dependsOn: ['recap_hard'],
    position: {
      x: 61.5,
      y: 46,
    },
  },
  rewrite: {
    type: 'feedback',
    done: false,
    time: 10,
    title: 'Feedback and Rewriting your opinion',
    labels: ['solo', 'ai'],
    contentType: 'Methode',
    nextExercises: ['fork3'],
    dependsOn: ['writing_easy', 'writing_hard'],
    position: {
      x: 48,
      y: 62,
    },
  },
  fork3: {
    type: 'fork',
    done: false,
    nextExercises: ['reflection', 'extra2'],
    dependsOn: ['rewrite'],
    position: {
      x: 60,
      y: 0,
    },
  },
  reflection: {
    type: 'reflection',
    done: false,
    time: 8,
    title: 'Reflection',
    labels: ['solo', 'ai'],
    contentType: 'Methode',
    nextExercises: null,
    dependsOn: ['rewrite'],
    position: {
      x: 47,
      y: 74.5,
    },
  },
  extra2: {
    type: 'excursion',
    done: false,
    time: 5,
    title: 'Knowing & recognising criteria for opinion writing',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: null,
    dependsOn: ['rewrite'],
    position: {
      x: 62,
      y: 62,
    },
  },
}
