import { MapItemsRecord } from './types'

export const localStorageKey = 'lernpfad_prototype'

export const initialMapItemsData: MapItemsRecord = {
  intro: {
    type: 'start',
    done: false,
    time: 5,
    title: 'Start',
    labels: ['group'],
    contentType: 'Inhalt',
    nextExercises: ['extra1', 'info'],
    dependsOn: null,
    position: {
      x: 47,
      y: 13,
    },
  },
  fork1: {
    type: 'fork',
    done: false,
    choice: null,
    nextExercises: ['extra1', 'info'],
    dependsOn: ['intro'],
    position: {
      x: 48,
      y: 24,
    },
  },
  extra1: {
    type: 'excursion',
    done: false,
    time: 5,
    title: 'Useful phrases & vocabulary',
    labels: ['solo'],
    contentType: 'Übung',
    isMacroadaptive: true,
    nextExercises: null,
    dependsOn: ['fork1'],
    position: {
      x: 37,
      y: 20,
    },
  },
  info: {
    type: 'info',
    done: false,
    time: 5,
    title: 'Information',
    labels: ['solo'],
    contentType: 'Inhalt',
    nextExercises: ['fork2'],
    dependsOn: ['fork1'],
    position: {
      x: 44,
      y: 28,
    },
  },
  fork2: {
    type: 'fork',
    done: false,
    choice: null,
    nextExercises: ['recap_easy', 'recap_hard'],
    dependsOn: ['info'],
    position: {
      x: 46,
      y: 38.5,
    },
  },
  recap_easy: {
    type: 'recap',
    done: false,
    time: 10,
    title: 'Cats or Dogs? 🐱 🐶',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: ['writing_easy'],
    dependsOn: ['fork2'],
    position: {
      x: 36.5,
      y: 43,
    },
  },
  recap_hard: {
    type: 'recap',
    done: false,
    time: 10,
    title: 'Cats or Dogs? 🐱 🐶',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: ['writing_hard'],
    dependsOn: ['fork2'],
    position: {
      x: 54.5,
      y: 39,
    },
  },
  writing_easy: {
    type: 'write',
    done: false,
    time: 20,
    title: 'Writing your opinion',
    labels: ['solo', 'ai'],
    contentType: 'Übung',
    nextExercises: ['rewrite'],
    dependsOn: ['recap_easy'],
    position: {
      x: 36,
      y: 57,
    },
  },
  writing_hard: {
    type: 'write',
    done: false,
    time: 20,
    title: 'Writing your opinion',
    labels: ['solo', 'ai'],
    contentType: 'Übung',
    isMacroadaptive: true,
    nextExercises: ['rewrite'],
    dependsOn: ['recap_hard'],
    position: {
      x: 57,
      y: 53,
    },
  },
  rewrite: {
    type: 'feedback',
    done: false,
    time: 10,
    title: 'Improving your opinion',
    labels: ['solo', 'ai'],
    contentType: 'Methode',
    nextExercises: ['fork3'],
    dependsOn: ['writing_easy', 'writing_hard'],
    position: {
      x: 47.5,
      y: 65,
    },
  },
  fork3: {
    type: 'fork',
    done: false,
    choice: null,
    nextExercises: ['reflection', 'extra2'],
    dependsOn: ['rewrite'],
    position: {
      x: 47.5,
      y: 75.5,
    },
  },
  reflection: {
    type: 'reflection',
    done: false,
    time: 8,
    title: 'Reflection',
    labels: ['solo', 'ai'],
    contentType: 'Methode',
    nextExercises: null,
    dependsOn: ['fork3'],
    position: {
      x: 46.5,
      y: 83,
    },
  },
  extra2: {
    type: 'excursion',
    done: false,
    time: 5,
    title: 'Knowing & recognising criteria for opinion writing',
    labels: ['solo'],
    contentType: 'Übung',
    nextExercises: null,
    dependsOn: ['fork3'],
    position: {
      x: 56,
      y: 71.5,
    },
  },
}
