# Update merged PRs in Deployment PR
name: Update Merged PRs
on:
  pull_request:
    branches:
      - merge-log-tester
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo merged $PR_NUMBER
